### PR TITLE
sl: updated to 5.03

### PR DESCRIPTION
**Pull request by beefcurtains**
You should really use a branch, here's how:
```
git checkout -b sl
git push origin sl
git checkout master
git reset --hard HEAD^
git push --force origin master
```
Where ``HEAD^`` refers to the latest upstream commit in the log. If you add the upstream remote and pull from it (while on the master branch), it should always fast-forward.

~~Travis is having a seizure, so it might not yet build there.~~ *EDIT: The build actually fails, looks like you still have some work to do! :smile: On the flipside, if it has to be fixed upstream I'll gladly accept the PR with the fix* :wink: When adjusting the template, try fixing things before applying workarounds.

Enjoy!

### CODE REVIEW

**Comment by kylesusername** [comment]
Thanks so much for the help, I've only recently started using git. I know, it was an absolutely disgusting hack. It seems that ncurses doesn't want to work on the ARM cross-compiler, despite it working just fine on native ARM with xbps-src and working fine on x86_64 and i686.

**Comment by beefcurtains** [comment]
It's all fixed now. Merge, rebase, ask xtraeme for forgiveness :scream:

**Comment by kylesusername** [comment]
For future templates. should I bother with `sed` trickery, or should I try to submit packages upstream?

**Comment by beefcurtains** [comment]
Not sure what you mean with submitting packages upstream, but generally we do whatever necessary to make it work. Forking the project is quite a rare occurrence, ``proplib`` is one, don't know any others.

**Comment by kylesusername** [comment]
Sorry, by submit packages upstream I meant submit patches upstream. I guess reading up on all of the variables for a `Makefile` would be a good start, as well.

**Comment by beefcurtains** [comment]
Sending patches upstream is done entirely at your own discretion.

**Pull request merged**
